Function to display results

##Python Code

In [1]:
print("Hello world!")

Hello world!


In [2]:
print("Hello world!", "I'm Alessio", 3, 0.5)

Hello world! I'm Alessio 3 0.5


In [3]:
import sys
print(sys.version)

3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]


#### Variables

named entities to store information

In [4]:
a = 2

In [5]:
type(a)

int

In [6]:
b = 0.2

In [7]:
type(b)

float

In [8]:
c = '10'

In [9]:
type(c)

str

In [10]:
float(c)

10.0

In [11]:
d = 'okokok'

In [12]:
float(d)

ValueError: could not convert string to float: 'okokok'

#### Numeric Operations

In [20]:
a = 5
b = 2
a,b

(5, 2)

In [21]:
a + b

7

In [22]:
a - b

3

In [23]:
a * b

10

In [24]:
a / b

2.5

In [25]:
a // b # floor division
## returns only integer part of the result

2

In [26]:
a % b # module (rest by integer division)

1

In [27]:
a ** b # exponentiation operator

25

#### Strings

In [28]:
s = "this is a string"
s

'this is a string'

In [29]:
len(s)

16

In [30]:
s + ' Alessio'

'this is a string Alessio'

In [31]:
r = s.replace("a", "THE")
r

'this is THE string'

In [32]:
r.upper()

'THIS IS THE STRING'

In [33]:
r.lower()

'this is the string'

In [34]:
s[0]

't'

In [35]:
s[1]

'h'

In [36]:
s[-1]

'g'

In [37]:
s[-2]

'n'

In [43]:
s[16]

IndexError: string index out of range

In [44]:
s[0:4]

'this'

In [45]:
s[5:10]

'is a '

#### Data Structures: Lists

In [46]:
my_first_list = [1, 3, 5, 10]

In [47]:
type(my_first_list)

list

In [48]:
my_first_list

[1, 3, 5, 10]

In [49]:
len(my_first_list)

4

In [50]:
my_first_list[0:2]

[1, 3]

In [51]:
my_first_list[-1]

10

In [52]:
foo = my_first_list + [9, 10, 3]

In [53]:
foo

[1, 3, 5, 10, 9, 10, 3]

In [54]:
my_first_set = set([1, 2, 5, 7, 7])

In [55]:
my_first_set

{1, 2, 5, 7}

In [56]:
my_first_set[0]

TypeError: 'set' object is not subscriptable

In [57]:
my_second_list = [3, 1.2, 'Alessio', False]

In [58]:
my_second_list

[3, 1.2, 'Alessio', False]

In [59]:
my_second_list.append('okokok')

In [60]:
my_second_list

[3, 1.2, 'Alessio', False, 'okokok']

In [61]:
my_second_set = set(my_second_list)

In [62]:
my_second_set

{1.2, 3, 'Alessio', False, 'okokok'}

In [63]:
type(my_second_set)

set

In [64]:
my_first_list.append(8)

In [65]:
my_first_list

[1, 3, 5, 10, 8]

In [66]:
my_second_list.append(my_first_list)

In [67]:
my_second_list

[3, 1.2, 'Alessio', False, 'okokok', [1, 3, 5, 10, 8]]

In [68]:
my_second_list[5]

[1, 3, 5, 10, 8]

In [69]:
# list functions

In [70]:
aaa = [1,2,3]
bbb = [3,4,5]

In [71]:
aaa + bbb

[1, 2, 3, 3, 4, 5]

In [72]:
ccc = aaa + bbb

In [73]:
aaa.append(3)

In [74]:
aaa

[1, 2, 3, 3]

In [75]:
aaa.extend(bbb)

In [76]:
aaa

[1, 2, 3, 3, 3, 4, 5]

In [77]:
# tuple
my_first_tuple = (1,2,3,3)

In [78]:
my_first_tuple # can contain duplicates

(1, 2, 3, 3)

In [79]:
my_first_tuple[0] # ordered can access by index

1

In [80]:
list(my_first_tuple)

[1, 2, 3, 3]

In [81]:
set(my_first_tuple) # does not contain duplicates

{1, 2, 3}

In [82]:
set(my_first_tuple)[0] # not ordered

TypeError: 'set' object is not subscriptable

In [83]:
my_first_tuple + (1,3)

(1, 2, 3, 3, 1, 3)

In [84]:
my_first_tuple * (3)

(1, 2, 3, 3, 1, 2, 3, 3, 1, 2, 3, 3)

In [85]:
set(my_first_tuple) | {2,3} # union operation

{1, 2, 3}

In [86]:
set(my_first_tuple) * {2,3}

TypeError: unsupported operand type(s) for *: 'set' and 'set'

In [87]:
my_first_tuple.append(0) # tuple not mutable

AttributeError: 'tuple' object has no attribute 'append'

In [88]:
my_set = set(my_first_tuple)
my_set

{1, 2, 3}

In [89]:
my_set.add(0)

In [90]:
my_set

{0, 1, 2, 3}

#### Dictionaries
mutable

In [91]:
my_first_dict = {'Alice': 10, 'Bob': 12, 'Charles': 16, 'Daisy':2}

In [92]:
my_first_dict

{'Alice': 10, 'Bob': 12, 'Charles': 16, 'Daisy': 2}

In [93]:
my_first_dict['Alice']

10

In [94]:
my_first_dict['Charles']

16

In [98]:
aaa = {1: 'Riccardo', 2: 'Alessio', 3: 'Dino'}

In [99]:
aaa[1]

'Riccardo'

In [100]:
aaa[0] = 'Alessandro'

In [101]:
aaa

{1: 'Riccardo', 2: 'Alessio', 3: 'Dino', 0: 'Alessandro'}

In [102]:
aaa[0] = 'Giuseppe'

In [103]:
aaa

{1: 'Riccardo', 2: 'Alessio', 3: 'Dino', 0: 'Giuseppe'}

In [104]:
len(aaa)

4

In [105]:
aaa.keys()

dict_keys([1, 2, 3, 0])

In [106]:
list(aaa.keys())

[1, 2, 3, 0]

In [107]:
aaa.values()

dict_values(['Riccardo', 'Alessio', 'Dino', 'Giuseppe'])

In [108]:
list(aaa.values())

['Riccardo', 'Alessio', 'Dino', 'Giuseppe']

In [109]:
aaa.items()

dict_items([(1, 'Riccardo'), (2, 'Alessio'), (3, 'Dino'), (0, 'Giuseppe')])

In [110]:
for key, value in aaa.items():
    print(key, value)

1 Riccardo
2 Alessio
3 Dino
0 Giuseppe


#### Conditional
if-else

In [111]:
a = 30
if a >= 25:
    b = 'Happy'
    print('Here')
else:
    b = 'Sad'
    print('There')

print('I\'m %s because I got %s to DM exam.' % (b, a))

Here
I'm Happy because I got 30 to DM exam.


In [112]:
a >= 25

True

In [113]:
a = 24
if 20 <= a < 25:
    print('AAAA')

AAAA


In [114]:
a > 30

False

#### loops

In [115]:
my_first_list

[1, 3, 5, 10, 8]

In [116]:
print(my_first_list[0])
print(my_first_list[1])
print(my_first_list[2])
...
print(my_first_list[7])

1
3
5


IndexError: list index out of range

In [117]:
for e in my_first_list:
    if e > 5:
        print(e)
    else:
        print('ooo')

ooo
ooo
ooo
10
8


In [118]:
for idx, e in enumerate(my_first_list):
    print(idx, e)

0 1
1 3
2 5
3 10
4 8


In [119]:
for i in range(len(my_first_list)):
    print(i, my_first_list[i])

0 1
1 3
2 5
3 10
4 8


In [120]:
for k, v in my_first_dict.items():
    print(k, v)

Alice 10
Bob 12
Charles 16
Daisy 2


#### Modules

In [121]:
# zen of python
# 19 principles for python

In [122]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [123]:
import math

In [124]:
math.pi

3.141592653589793

In [125]:
math.log2(1456)

10.507794640198696

## Numpy array

In [126]:
import numpy as np
# aliasing
# handles array and calculus
# fast, memory handeled well

In [127]:
my_first_array = np.array(my_first_list)

In [128]:
my_first_array

array([ 1,  3,  5, 10,  8])

In [129]:
my_first_list * 5

[1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8,
 1,
 3,
 5,
 10,
 8]

In [130]:
# pairwise operation
my_first_array * 5

array([ 5, 15, 25, 50, 40])

In [131]:
my_first_array / 5

array([0.2, 0.6, 1. , 2. , 1.6])

In [132]:
my_first_array + my_first_array

array([ 2,  6, 10, 20, 16])

In [133]:
# other ways of creating loops

In [134]:
for i in np.arange(1, 20, 5):
    print(i)

1
6
11
16


In [135]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [136]:
range(10)

range(0, 10)

In [137]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


## Pandas e Sklearn

In [138]:
import pandas as pd
from sklearn.datasets import load_iris

In [139]:
data = load_iris()

In [140]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [141]:
print(data['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [142]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [143]:
data['data'].shape

(150, 4)

In [144]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [145]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [146]:
iris_df = pd.DataFrame(data['data'], columns = data['feature_names'])
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [147]:
iris_df_target = iris_df.copy()

In [148]:
iris_df_target['target'] = data['target']

In [149]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [153]:
# import dataset from local disk
#df = pd.read_csv("data/iris.csv", skipinitialspace=True)
#df

In [155]:
df = iris_df

In [156]:
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [157]:
df.shape  # (n_rows, n_columns)

(150, 4)

In [158]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [160]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

#### Access to elements

In [174]:
df = df.rename(columns = {'sepal length (cm)' : 'sepal length',
                          'sepal width (cm)' : 'sepal width',
                          'petal length (cm)' : 'petal length',
                          'petal width (cm)' : 'petal width'}
                          )
df

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [175]:
# access columns
df.loc[:, "sepal length"] #consider the "sepal length" column
df.iloc[:, 0] #consider to the column 0
df["sepal length"] #consider the sepal lenght columns

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length, Length: 150, dtype: float64

In [176]:
df[["sepal length"]]

sepal length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [177]:
type(df["sepal length"]), type(df[["sepal length"]]) #they share different types, the first is a SERIES, the second a dataframe

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [178]:
df[["sepal length", "petal length"]]

sepal length  petal length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [179]:
# access rows
df.iloc[0, :]

sepal length    5.1
sepal width     3.5
petal length    1.4
petal width     0.2
Name: 0, dtype: float64

In [180]:
df.iloc[0, :]

sepal length    5.1
sepal width     3.5
petal length    1.4
petal width     0.2
Name: 0, dtype: float64

In [181]:
df.iloc[0]

sepal length    5.1
sepal width     3.5
petal length    1.4
petal width     0.2
Name: 0, dtype: float64

In [182]:
df.head(1)

sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2

In [183]:
# access elements
df["sepal length"][0]
df.iloc[0]["sepal length"]
df.iloc[0, 0]
df.loc[0, "sepal length"]

np.float64(5.1)

In [184]:
type(df["sepal length"][0])

numpy.float64

In [185]:
df.index


RangeIndex(start=0, stop=150, step=1)

In [186]:
df.columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width'], dtype='object')

In [189]:
df

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [190]:
df.T #transpose the dataset

0    1    2    3    4    5    6    7    8    9    ...  140  141  \
sepal length  5.1  4.9  4.7  4.6  5.0  5.4  4.6  5.0  4.4  4.9  ...  6.7  6.9   
sepal width   3.5  3.0  3.2  3.1  3.6  3.9  3.4  3.4  2.9  3.1  ...  3.1  3.1   
petal length  1.4  1.4  1.3  1.5  1.4  1.7  1.4  1.5  1.4  1.5  ...  5.6  5.1   
petal width   0.2  0.2  0.2  0.2  0.2  0.4  0.3  0.2  0.2  0.1  ...  2.4  2.3   

              142  143  144  145  146  147  148  149  
sepal length  5.8  6.8  6.7  6.7  6.3  6.5  6.2  5.9  
sepal width   2.7  3.2  3.3  3.0  2.5  3.0  3.4  3.0  
petal length  5.1  5.9  5.7  5.2  5.0  5.2  5.4  5.1  
petal width   1.9  2.3  2.5  2.3  1.9  2.0  2.3  1.8  

[4 rows x 150 columns]

#### Modyfing dataframes

In [191]:
df_copy = df.copy()

In [192]:
df_copy2 = df

In [193]:
df_copy2["new_column"] = list(range(len(df)))  # add column
df_copy2.loc[len(df_copy2)] = list(range(len(df_copy2.columns)))  # add row

In [194]:
df_copy

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [195]:
df_copy2

sepal length  sepal width  petal length  petal width  new_column
0             5.1          3.5           1.4          0.2           0
1             4.9          3.0           1.4          0.2           1
2             4.7          3.2           1.3          0.2           2
3             4.6          3.1           1.5          0.2           3
4             5.0          3.6           1.4          0.2           4
..            ...          ...           ...          ...         ...
146           6.3          2.5           5.0          1.9         146
147           6.5          3.0           5.2          2.0         147
148           6.2          3.4           5.4          2.3         148
149           5.9          3.0           5.1          1.8         149
150           0.0          1.0           2.0          3.0           4

[151 rows x 5 columns]

#### Converting between data structures (pd.Dataframe, np.array, list of lists)

In [196]:
df.values ##gives a numpy array

array([[5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01, 0.00e+00],
       [4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01, 1.00e+00],
       [4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01, 2.00e+00],
       [4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01, 3.00e+00],
       [5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01, 4.00e+00],
       [5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01, 5.00e+00],
       [4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01, 6.00e+00],
       [5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01, 7.00e+00],
       [4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01, 8.00e+00],
       [4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01, 9.00e+00],
       [5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01, 1.00e+01],
       [4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01, 1.10e+01],
       [4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01, 1.20e+01],
       [4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01, 1.30e+01],
       [5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01, 1.40e+01],
       [5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01, 1.50e+01],
       [5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01, 1.60e+01

In [197]:
df.values.tolist()

[[5.1, 3.5, 1.4, 0.2, 0.0],
 [4.9, 3.0, 1.4, 0.2, 1.0],
 [4.7, 3.2, 1.3, 0.2, 2.0],
 [4.6, 3.1, 1.5, 0.2, 3.0],
 [5.0, 3.6, 1.4, 0.2, 4.0],
 [5.4, 3.9, 1.7, 0.4, 5.0],
 [4.6, 3.4, 1.4, 0.3, 6.0],
 [5.0, 3.4, 1.5, 0.2, 7.0],
 [4.4, 2.9, 1.4, 0.2, 8.0],
 [4.9, 3.1, 1.5, 0.1, 9.0],
 [5.4, 3.7, 1.5, 0.2, 10.0],
 [4.8, 3.4, 1.6, 0.2, 11.0],
 [4.8, 3.0, 1.4, 0.1, 12.0],
 [4.3, 3.0, 1.1, 0.1, 13.0],
 [5.8, 4.0, 1.2, 0.2, 14.0],
 [5.7, 4.4, 1.5, 0.4, 15.0],
 [5.4, 3.9, 1.3, 0.4, 16.0],
 [5.1, 3.5, 1.4, 0.3, 17.0],
 [5.7, 3.8, 1.7, 0.3, 18.0],
 [5.1, 3.8, 1.5, 0.3, 19.0],
 [5.4, 3.4, 1.7, 0.2, 20.0],
 [5.1, 3.7, 1.5, 0.4, 21.0],
 [4.6, 3.6, 1.0, 0.2, 22.0],
 [5.1, 3.3, 1.7, 0.5, 23.0],
 [4.8, 3.4, 1.9, 0.2, 24.0],
 [5.0, 3.0, 1.6, 0.2, 25.0],
 [5.0, 3.4, 1.6, 0.4, 26.0],
 [5.2, 3.5, 1.5, 0.2, 27.0],
 [5.2, 3.4, 1.4, 0.2, 28.0],
 [4.7, 3.2, 1.6, 0.2, 29.0],
 [4.8, 3.1, 1.6, 0.2, 30.0],
 [5.4, 3.4, 1.5, 0.4, 31.0],
 [5.2, 4.1, 1.5, 0.1, 32.0],
 [5.5, 4.2, 1.4, 0.2, 33.0],
 [4.9, 3.1, 1.5, 0.2, 34

In [198]:
X = df.values
X_list = df.values.tolist()

In [199]:
type(df), type(X), type(X_list)

(pandas.core.frame.DataFrame, numpy.ndarray, list)

In [200]:
X_list

[[5.1, 3.5, 1.4, 0.2, 0.0],
 [4.9, 3.0, 1.4, 0.2, 1.0],
 [4.7, 3.2, 1.3, 0.2, 2.0],
 [4.6, 3.1, 1.5, 0.2, 3.0],
 [5.0, 3.6, 1.4, 0.2, 4.0],
 [5.4, 3.9, 1.7, 0.4, 5.0],
 [4.6, 3.4, 1.4, 0.3, 6.0],
 [5.0, 3.4, 1.5, 0.2, 7.0],
 [4.4, 2.9, 1.4, 0.2, 8.0],
 [4.9, 3.1, 1.5, 0.1, 9.0],
 [5.4, 3.7, 1.5, 0.2, 10.0],
 [4.8, 3.4, 1.6, 0.2, 11.0],
 [4.8, 3.0, 1.4, 0.1, 12.0],
 [4.3, 3.0, 1.1, 0.1, 13.0],
 [5.8, 4.0, 1.2, 0.2, 14.0],
 [5.7, 4.4, 1.5, 0.4, 15.0],
 [5.4, 3.9, 1.3, 0.4, 16.0],
 [5.1, 3.5, 1.4, 0.3, 17.0],
 [5.7, 3.8, 1.7, 0.3, 18.0],
 [5.1, 3.8, 1.5, 0.3, 19.0],
 [5.4, 3.4, 1.7, 0.2, 20.0],
 [5.1, 3.7, 1.5, 0.4, 21.0],
 [4.6, 3.6, 1.0, 0.2, 22.0],
 [5.1, 3.3, 1.7, 0.5, 23.0],
 [4.8, 3.4, 1.9, 0.2, 24.0],
 [5.0, 3.0, 1.6, 0.2, 25.0],
 [5.0, 3.4, 1.6, 0.4, 26.0],
 [5.2, 3.5, 1.5, 0.2, 27.0],
 [5.2, 3.4, 1.4, 0.2, 28.0],
 [4.7, 3.2, 1.6, 0.2, 29.0],
 [4.8, 3.1, 1.6, 0.2, 30.0],
 [5.4, 3.4, 1.5, 0.4, 31.0],
 [5.2, 4.1, 1.5, 0.1, 32.0],
 [5.5, 4.2, 1.4, 0.2, 33.0],
 [4.9, 3.1, 1.5, 0.2, 34

In [201]:
X[0, 0]

np.float64(5.1)

In [202]:
X_list[0][0]

5.1

In [203]:
X_list[0]

[5.1, 3.5, 1.4, 0.2, 0.0]

In [204]:
X[0,:]

array([5.1, 3.5, 1.4, 0.2, 0. ])

In [205]:
pd.Series(X[0,:])

0    5.1
1    3.5
2    1.4
3    0.2
4    0.0
dtype: float64

In [206]:
list(X[0,:])

[np.float64(5.1),
 np.float64(3.5),
 np.float64(1.4),
 np.float64(0.2),
 np.float64(0.0)]

In [207]:
(X[0,:]).tolist()

[5.1, 3.5, 1.4, 0.2, 0.0]

In [208]:
X[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 0. ])

#### Filtering

In [212]:
df[df["sepal length"] > 5.1]

sepal length  sepal width  petal length  petal width  new_column
5             5.4          3.9           1.7          0.4           5
10            5.4          3.7           1.5          0.2          10
14            5.8          4.0           1.2          0.2          14
15            5.7          4.4           1.5          0.4          15
16            5.4          3.9           1.3          0.4          16
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3         145
146           6.3          2.5           5.0          1.9         146
147           6.5          3.0           5.2          2.0         147
148           6.2          3.4           5.4          2.3         148
149           5.9          3.0           5.1          1.8         149

[109 rows x 5 columns]

In [218]:
df[(df["sepal length"] > 1.4) & (df["petal width"] < 4.9)]

sepal length  sepal width  petal length  petal width  new_column
0             5.1          3.5           1.4          0.2           0
1             4.9          3.0           1.4          0.2           1
2             4.7          3.2           1.3          0.2           2
3             4.6          3.1           1.5          0.2           3
4             5.0          3.6           1.4          0.2           4
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3         145
146           6.3          2.5           5.0          1.9         146
147           6.5          3.0           5.2          2.0         147
148           6.2          3.4           5.4          2.3         148
149           5.9          3.0           5.1          1.8         149

[150 rows x 5 columns]

In [223]:
df['petal length'].mean()

np.float64(3.74635761589404)

#### Apply vs iterating

In [224]:
df.iloc[:, :4].apply(np.sqrt)

sepal length  sepal width  petal length  petal width
0        2.258318     1.870829      1.183216     0.447214
1        2.213594     1.732051      1.183216     0.447214
2        2.167948     1.788854      1.140175     0.447214
3        2.144761     1.760682      1.224745     0.447214
4        2.236068     1.897367      1.183216     0.447214
..            ...          ...           ...          ...
146      2.509980     1.581139      2.236068     1.378405
147      2.549510     1.732051      2.280351     1.414214
148      2.489980     1.843909      2.323790     1.516575
149      2.428992     1.732051      2.258318     1.341641
150      0.000000     1.000000      1.414214     1.732051

[151 rows x 4 columns]

In [225]:
def plus_two(x):
  return x + 2

In [226]:
df.iloc[:, :4].apply(np.sqrt)

sepal length  sepal width  petal length  petal width
0        2.258318     1.870829      1.183216     0.447214
1        2.213594     1.732051      1.183216     0.447214
2        2.167948     1.788854      1.140175     0.447214
3        2.144761     1.760682      1.224745     0.447214
4        2.236068     1.897367      1.183216     0.447214
..            ...          ...           ...          ...
146      2.509980     1.581139      2.236068     1.378405
147      2.549510     1.732051      2.280351     1.414214
148      2.489980     1.843909      2.323790     1.516575
149      2.428992     1.732051      2.258318     1.341641
150      0.000000     1.000000      1.414214     1.732051

[151 rows x 4 columns]

In [227]:
#X[:, :4]

In [228]:
df.iloc[:, :4].apply(plus_two)

sepal length  sepal width  petal length  petal width
0             7.1          5.5           3.4          2.2
1             6.9          5.0           3.4          2.2
2             6.7          5.2           3.3          2.2
3             6.6          5.1           3.5          2.2
4             7.0          5.6           3.4          2.2
..            ...          ...           ...          ...
146           8.3          4.5           7.0          3.9
147           8.5          5.0           7.2          4.0
148           8.2          5.4           7.4          4.3
149           7.9          5.0           7.1          3.8
150           2.0          3.0           4.0          5.0

[151 rows x 4 columns]

In [231]:
%%timeit
new_df = pd.DataFrame()
for i in range(df.shape[0]):
    new_df = pd.concat([new_df, pd.DataFrame(df.iloc[i] + 2).T], axis=0)
new_df

207 ms ± 84.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [232]:
def plustwo(a):
    return a + 2

df.iloc[:, :4].apply(lambda a: a + 2)
df.iloc[:, :4].apply(plustwo)

sepal length  sepal width  petal length  petal width
0             7.1          5.5           3.4          2.2
1             6.9          5.0           3.4          2.2
2             6.7          5.2           3.3          2.2
3             6.6          5.1           3.5          2.2
4             7.0          5.6           3.4          2.2
..            ...          ...           ...          ...
146           8.3          4.5           7.0          3.9
147           8.5          5.0           7.2          4.0
148           8.2          5.4           7.4          4.3
149           7.9          5.0           7.1          3.8
150           2.0          3.0           4.0          5.0

[151 rows x 4 columns]

In [233]:
%%timeit
df.iloc[:, :4].apply(plustwo)

646 µs ± 27.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [234]:
df.apply(lambda a: [str(i) + " ciao" for i in a])

sepal length sepal width petal length petal width new_column
0       5.1 ciao    3.5 ciao     1.4 ciao    0.2 ciao     0 ciao
1       4.9 ciao    3.0 ciao     1.4 ciao    0.2 ciao     1 ciao
2       4.7 ciao    3.2 ciao     1.3 ciao    0.2 ciao     2 ciao
3       4.6 ciao    3.1 ciao     1.5 ciao    0.2 ciao     3 ciao
4       5.0 ciao    3.6 ciao     1.4 ciao    0.2 ciao     4 ciao
..           ...         ...          ...         ...        ...
146     6.3 ciao    2.5 ciao     5.0 ciao    1.9 ciao   146 ciao
147     6.5 ciao    3.0 ciao     5.2 ciao    2.0 ciao   147 ciao
148     6.2 ciao    3.4 ciao     5.4 ciao    2.3 ciao   148 ciao
149     5.9 ciao    3.0 ciao     5.1 ciao    1.8 ciao   149 ciao
150     0.0 ciao    1.0 ciao     2.0 ciao    3.0 ciao     4 ciao

[151 rows x 5 columns]